#ifndef __MKTRACE_BIT_NUM
#define __MKTRACE_BIT_NUM

#define __BN_brk            (1)
#define __BN_chdir          (1 << 1)
#define __BN_chmod          (1 << 2) 
#define __BN_clock_gettime  (1 << 3) 
#define __BN_close          (1 << 5) 
#define __BN_dup            (1 << 6) 
#define __BN_dup2           (1 << 7) 
#define __BN_faccessat      (1 << 9) 
#define __BN_fchmod         (1 << 10) 
#define __BN_fchown         (1 << 11)
#define __BN_fcntl          (1 << 12)
#define __BN_fstat          (1 << 13)
#define __BN_futex          (1 << 14)
#define __BN_getcwd         (1 << 15)
#define __BN_getdents64     (1 << 16)
#define __BN_getegid        (1 << 17)
#define __BN_getgid         (1 << 19)
#define __BN_getpid         (1 << 22)
#define __BN_getppid        (1 << 23)
#define __BN_ioctl          (1 << 25)
#define __BN_lseek          (1 << 27)
#define __BN_lstat          (1 << 28)
#define __BN_mkdir          (1 << 29)
#define __BN_mprotect       (1 << 31)
#define __BN_read           (1 << 38)
#define __BN_readlink       (1 << 39)
#define __BN_sendto         (1 << 43)
#define __BN_setpgid        (1 << 44)
#define __BN_socket         (1 << 47)
#define __BN_stat           (1 << 48)
#define __BN_sysinfo        (1 << 49)
#define __BN_umask          (1 << 50)
#define __BN_uname          (1 << 51)
#define __BN_unlink         (1 << 52)
#define __BN_utime          (1 << 53)
#define __BN_wait4          (1 << 55)
#define __BN_write          (1 << 56)
#endif
